# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: montecarlo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'montecarlo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10montecarlo.proto\x12\nmontecarlo\"%\n\x10HandshakeRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"L\n\x0eHandshakeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x17\n\x0fpuntos_por_lote\x18\x03 \x01(\x05\x32Z\n\x11MonteCarloService\x12\x45\n\tHandshake\x12\x1c.montecarlo.HandshakeRequest\x1a\x1a.montecarlo.HandshakeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'montecarlo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKEREQUEST']._serialized_start=32
  _globals['_HANDSHAKEREQUEST']._serialized_end=69
  _globals['_HANDSHAKEREPLY']._serialized_start=71
  _globals['_HANDSHAKEREPLY']._serialized_end=147
  _globals['_MONTECARLOSERVICE']._serialized_start=149
  _globals['_MONTECARLOSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
