# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import montecarlo_pb2 as montecarlo__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in montecarlo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """===================================================
    Servicio gRPC
    ===================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerTarea = channel.unary_unary(
                '/montecarlo.TaskService/ObtenerTarea',
                request_serializer=montecarlo__pb2.ObtenerTareaRequest.SerializeToString,
                response_deserializer=montecarlo__pb2.ObtenerTareaResponse.FromString,
                _registered_method=True)
        self.EnviarResultado = channel.unary_unary(
                '/montecarlo.TaskService/EnviarResultado',
                request_serializer=montecarlo__pb2.EnviarResultadoRequest.SerializeToString,
                response_deserializer=montecarlo__pb2.EnviarResultadoResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """===================================================
    Servicio gRPC
    ===================================================

    """

    def ObtenerTarea(self, request, context):
        """RPC para que el cliente solicite una nueva tarea.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarResultado(self, request, context):
        """RPC para que el cliente envíe el resultado de una tarea.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerTarea': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerTarea,
                    request_deserializer=montecarlo__pb2.ObtenerTareaRequest.FromString,
                    response_serializer=montecarlo__pb2.ObtenerTareaResponse.SerializeToString,
            ),
            'EnviarResultado': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarResultado,
                    request_deserializer=montecarlo__pb2.EnviarResultadoRequest.FromString,
                    response_serializer=montecarlo__pb2.EnviarResultadoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'montecarlo.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('montecarlo.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """===================================================
    Servicio gRPC
    ===================================================

    """

    @staticmethod
    def ObtenerTarea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/montecarlo.TaskService/ObtenerTarea',
            montecarlo__pb2.ObtenerTareaRequest.SerializeToString,
            montecarlo__pb2.ObtenerTareaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarResultado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/montecarlo.TaskService/EnviarResultado',
            montecarlo__pb2.EnviarResultadoRequest.SerializeToString,
            montecarlo__pb2.EnviarResultadoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
